[tools]
node = "lts"
opentofu = "1.8.6"
python = "3.12"
rust = "latest"
terragrunt = "0.83.2"

[settings]
idiomatic_version_file_enable_tools = [
  'node',
  'terraform',
  'python-version',
  'go-version',
]
