return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "dockerfile",
        "go",
        "gomod",
        "gowork",
        "gosum",
        "hcl",
        "hcl",
        "html",
        "javascript",
        "json",
        "markdown",
        "markdown_inline",
        "python",
        "python",
        "query",
        "regex",
        "rust",
        "terraform",
        "toml",
        "tsx",
        "typescript",
        "yaml",
      },
    },
  },
}
